### ISSUE TITLE
Does it work for infrared ?

### ISSUE THREAD

**Issue by admasson** [Hoeijmakers/StarRotator#54]
Hi Jens,

Does StarRotator work for infrared (e.g. up to 2.5 microns) observations? I guess it would, as PHOENIX and pySME can cover this spectral range, but I wanted to ask to be sure.

Also many thanks to you and your team for setting up a public tool like this, it will help a lot in dealing with the RME!

Cheers,
Adrien Masson

**Comment by jseideleso** [comment]
Hi Adrien,

this shouldn't be an issue. E.g. pySME uses the VALD line list. So as long as you are happy with the provided NIR lines in VALD for your application purposes (and I assume that is the case), then you should be good to go!

Cheers,
Julia
