### ISSUE TITLE
fx_list referenced before assignment

### ISSUE THREAD

**Issue by bprinoth** [Hoeijmakers/StarRotator#57]
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[5], line 24
      1 #When using the dictionary:
      2 input_dictionary = {
      3                       'veq':0.0, # 
      4                       'stelinc': 90.0, #stellar inclination axis, degrees, float
   (...)
     21                       'phases': phases #numpy array, set to the orbital phases of the time series
     22                     }
---> 24 Planet = StarRotator(586.0,592.0,10.0,input=input_dictionary)

File ~/GitHub/StarRotator/StarRotator.py:144, in StarRotator.__init__(self, wave_start, wave_end, grid_size, star_path, planet_path, obs_path, input, linelist_path)
    142 self.linelist_path = linelist_path
    143 self.read_system(star_path=star_path,planet_path=planet_path,obs_path=obs_path,input=input)
--> 144 self.compute_spectrum()

File ~/GitHub/StarRotator/StarRotator.py:375, in StarRotator.compute_spectrum(self)
    373 self.wl = wlF
    374 self.stellar_spectrum = F
--> 375 self.fx_list = copy.deepcopy(fx_list)
    376 self.Fp = copy.deepcopy(F_planet)
    377 self.spectra = copy.deepcopy(F_out)

UnboundLocalError: local variable 'fx_list' referenced before assignment

**Comment by bprinoth** [comment]
This is due to an error in the documentation. Me fix.

**Comment by bprinoth** [comment]
the phoenix option does not work because fx_list is not defined

**Comment by bprinoth** [comment]
Fixed with PR #61

**Comment by Hoeijmakers** [comment]
Thanks!
